### PR TITLE
fix(autobuild): update script for void

### PR DESCRIPTION
**Pull request by skyler544**
This fixed two errors with the autobuild script on my setup; I'm new to Void Linux so I'm not entirely sure if these problems are typical, but they may be of interest for others.

### CODE REVIEW

**Comment by vedang** [comment]
Can you print the output of /etc/os-release on Void? Specifically, I want to record it for posterity and I want to see if we can move to using the $ID field instead of using the $NAME field in this way.

**Comment by skyler544** [comment]
```
NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"
```

**Comment by vedang** [comment]
@skyler544 : Great. Please change the $NAME check in the autobuild script to use $ID = void instead.

**Comment by vedang** [comment]
I think `/usr/lib/` is too generic a path for requirement with `pkg-config`. Can you print out what the default pkg-config path on void is? Print the output of these two commands

1. `pkg-config --variable pc_path pkg-config`
2. `echo $PKG_CONFIG_PATH`

**Comment by skyler544** [comment]
Here's the output of 1:
`/usr/lib64/pkgconfig:/usr/share/pkgconfig`
And 2:

(nothing is set here by default)

**Comment by skyler544** [comment]
I think that a better solution for the `pkgconfig` path is this: `/usr/lib/pkgconfig`; I tried grepping for this in the files provided by the dependencies and that seems to be the common directory for these files. Changing the path to that allowed me to successfully build the `epdfinfo` executable.

**Pull request closed without merging**
