### PR TITLE
Let bind org-preview-latex-default-process to 'dvipng in pdf-annot-print-annotation-latex

### PR DESCRIPTION
**Pull request by vizs**
Users might have changed `org-preview-latex-default-process` from its default value of 'dvipng.  And pdf-tools can only work with png files currently, so let binding will ensure that pdf-tools can print the latex-preview regardless of the user configuration.

### CODE REVIEW

**Comment by vedang** [comment]
Thanks, looks good to me. Will test and merge in a few days.

**Comment by vizs** [comment]
Great, thanks!

**Comment by vedang** [comment]
While this change makes total sense, the problem is that `org-preview-latex-default-process` was only introduced in Emacs 26.1. This breaks compatibility with current `pdf-tools`, which supports Emacs all the way back to 24.3.

If you want to me to merge this in immediately, you need to investigate `org-latex-create-formula-image-program` as well, which is the older alias for this code, and set the correct variable based on what is bound.

**Comment by vizs** [comment]
30 Dec 2021, 21:16 by ***@***.***:

>
>
>
>
> While this change makes total sense, the problem is that > org-preview-latex-default-process>  was only introduced in Emacs 26.1. This breaks compatibility with current > pdf-tools> , which supports Emacs all the way back to 24.3.
>
>
I see, I didn't check previous Emacs releases.
>
> If you want to me to merge this in immediately, you need to investigate > org-latex-create-formula-image-program>  as well, which is the older alias for this code, and set the correct variable based on what is bound.
>
Right, I will look into this.

**Comment by vizs** [comment]
I checked the org repo for information about compatibility with previous
releases, mainly how long they keep the obsolete aliases around but I
didn't find anything concrete.  I did however find the org maintenance
page on worg (https://orgmode.org/worg/org-maintenance.html) and it
says,

>We aim at keeping the latest stable version of Org compatible with the
>last three major releases of Emacs.
>
>For example, if the latest release of Emacs is 28.x, then you can
>assume that the latest release of Org is compatible with Emacs 28.x,
>27.x and 26.x, but not with Emacs 25.x.

which is not exactly clear to me.

org-latex-create-formula-image-program is still defined as an obsolete
alias in the org main branch, so should we let-bind it instead or go
with following ugly (IMO) patch?

```diff
diff --git a/lisp/pdf-annot.el b/lisp/pdf-annot.el
index fcf184e..fdd56e9 100644
--- a/lisp/pdf-annot.el
+++ b/lisp/pdf-annot.el
@@ -1340,7 +1340,9 @@ by a header."
                                 "pdf-annot-print-annotation-latex%s%s%s"
                                 page header contents)))
                  (data (pdf-cache-lookup-image page 0 nil hash))
-                 (org-preview-latex-default-process 'dvipng)
+                 (old-ltx-proc (if (boundp 'org-preview-latex-default-process)
+                                   org-preview-latex-default-process
+                                 org-latex-create-formula-image-program))
                  (org-format-latex-header
                   pdf-annot-latex-header)
                  (temporary-file-directory
@@ -1351,8 +1353,14 @@ by a header."
               (setq tempfile (make-temp-file "pdf-annot" nil ".png"))
               ;; FIXME: Why is this with-temp-buffer needed (which it is) ?
               (with-temp-buffer
+                (if (boundp 'org-preview-latex-default-process)
+                    (setq org-preview-latex-default-process 'dvipng)
+                  (setq org-latex-create-formula-image-program 'dvipng))
                 (org-create-formula-image
                  contents tempfile org-format-latex-options t))
+              (if (boundp 'org-preview-latex-default-process)
+                  (setq org-preview-latex-default-process old-ltx-proc)
+                (setq org-latex-create-formula-image-program old-ltx-proc))
               (setq data (pdf-util-munch-file tempfile))
               (if (and (> (length data) 3)
                        (equal (substring data 1 4)
```

**Comment by vedang** [comment]
I'll be following the same policy (supporting 3 versions of Emacs) and will be raising minimum Emacs version to 25.1. This means that `pdf-tools` will have to handle both `org-preview-latex-default-process` as well as `org-latex-create-formula-image-program`. However, I don't see the problem in simply defining both these variables to `'dvipng` in the `let*` binding. Since the effect is local to the closure, it should be fine. You can modify the patch to include both, with a comment stating that the second one is for backward compatibility for Emacs Version < 26.

**Comment by vizs** [comment]
Oh, that was a complete brain-fart on my part.  I was thinking let-binding org-latex-create-formula-image-program would signal an error.  So much for replying just as I woke up, I guess.

**Comment by vedang** [comment]
👍 I will squash the change and merge it in.

**Pull request closed without merging**
